name: Java CI with Maven

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu
    container:
      image: ubuntu:24.04

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Start Notebook manager
        run: docker-compose -f src/test/resources/docker/docker-compose.yml up -d

      - name: Run tests
        run: mvn clean test -B -Plocal,allure-reports -DhidePollingProgress

      - name: Stop Notebook manager
        if: always()
        run: docker-compose -f src/test/resources/docker/docker-compose.yml down

      - name: Get Allure history
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure reports
        uses: simple-elf/allure-report-action@master
        if: always()
        #id: allure-report
        with:
          allure_results: target/allure-results
          #gh_pages: gh-pages
          #allure_report: allure-report
          allure_history: allure-history
          keep_reports: 3

      - name: Deploy Allure reports to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
